export const cookies = [
    {
        "domain": ".linkedin.com",
        "expirationDate": 1750602373.956315,
        "hostOnly": false,
        "httpOnly": false,
        "name": "lms_ads",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "AQEvW1X0Aj3IEwAAAZb9iZCf3_8arBb_zKSmnczadlegUrvYVIj7AoSg2PXv42LuqhbQfMl3mjJd5-BMSP85NCRs71i6tjeY"
    },
    {
        "domain": ".linkedin.com",
        "expirationDate": 1752470966.866112,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_guid",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "d65e0ad4-6032-4178-9e5e-5de4ad2a8be0"
    },
    {
        "domain": ".linkedin.com",
        "expirationDate": 1779547271.258987,
        "hostOnly": false,
        "httpOnly": false,
        "name": "bcookie",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "\"v=2&59ca5b0e-9506-4435-83b5-cc37e88f1f07\""
    },
    {
        "domain": ".linkedin.com",
        "expirationDate": 1748012322.572032,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__cf_bm",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "WNk2sBKn3bsis969F45zc2EV2ur5Nh78XqBRBfLCfsI-1748010522-1.0.1.1-kZ5dMSZVNUNQ6AATK3.DVsH82xp1P0xYpSP7KDfQFgC07W1QJEVRh4v9cXt3lBftTeLi7Pg9S8F.Z.g3ZcB_t41osTJbmwoZ_5607RC2Pbc"
    },
    {
        "domain": ".linkedin.com",
        "expirationDate": 1750602373.956431,
        "hostOnly": false,
        "httpOnly": false,
        "name": "lms_analytics",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "AQEvW1X0Aj3IEwAAAZb9iZCf3_8arBb_zKSmnczadlegUrvYVIj7AoSg2PXv42LuqhbQfMl3mjJd5-BMSP85NCRs71i6tjeY"
    },
    {
        "domain": ".linkedin.com",
        "hostOnly": false,
        "httpOnly": true,
        "name": "fptctx2",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": true,
        "storeId": null,
        "value": "taBcrIH61PuCVH7eNCyH0OPzOrGnaCb%252f7mTjN%252fuIW2tlaEmReZPB%252f6%252fBy6TZykYNyoKrHYCMmM34NBY77qDbVxnReeSfAyrJ9uNEXjRlhJWThLiTDwksGfhkVyFpb99mK4hWQmXKnmHrFaAfIuUXo44033pMu07mghH%252fHEgFUYRTQNl%252fn%252f1Nt9yPMvK3SmR0qjRdLBo7a%252bLiYn%252boRxr23todRHCUosn2k32CpGpqaLB8RR6R1s3f1LptLYk5uFvfV8DpyoFQa1vtf1vc98J%252fJMnBUGLWzgWMx7hMfbnL7YBXROWhPCnoxqAigXEn%252fL%252bJafyI1kG2Lk3uXoRLYXWeezVXK%252fmDLNjUSr64mCYg%252f9E%253d"
    },
    {
        "domain": ".www.linkedin.com",
        "expirationDate": 1779546370.056073,
        "hostOnly": false,
        "httpOnly": true,
        "name": "li_at",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "AQEDATcMmc8FYcG4AAABljfsNgUAAAGXIZYE9k4AzLXLC6CPontQCZRezphFQ_1i-BevzYOx1BBS_Om27geYGvDOBGQjJG02HlW_aq71kkP8M24Cdc-ly_HrKvj5v5n8FEk43LA__Wq4yINib1f4B2Kl"
    },
    {
        "domain": ".linkedin.com",
        "hostOnly": false,
        "httpOnly": false,
        "name": "lang",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": true,
        "storeId": null,
        "value": "v=2&lang=en-us"
    },
    {
        "domain": ".linkedin.com",
        "expirationDate": 1748096770.276021,
        "hostOnly": false,
        "httpOnly": false,
        "name": "lidc",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "\"b=OB87:s=O:r=O:a=O:p=O:g=3335:u=86:x=1:i=1748011271:t=1748096769:v=2:sig=AQH8pJhU07oOSYTpXhZHxUn374XJLnI4\""
    },
    {
        "domain": ".linkedin.com",
        "expirationDate": 1750602373.467802,
        "hostOnly": false,
        "httpOnly": false,
        "name": "AnalyticsSyncHistory",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "AQLjhCG5n_tXRgAAAZb9iY9IB5VnG9B789-nR14UJio4zj95DLT2rHQxIoiPVXFybRvyetxWEvUuLgi_lHfU7g"
    },
    {
        "domain": ".www.linkedin.com",
        "expirationDate": 1779547208.251817,
        "hostOnly": false,
        "httpOnly": true,
        "name": "bscookie",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "\"v=1&20250415052857098b01d1-42cf-4f90-8c80-7c1df25212cfAQH-Lk_cOdWxO4a33WwqIRD1Qef4WDEo\""
    },
    {
        "domain": ".linkedin.com",
        "expirationDate": 1776230977.598593,
        "hostOnly": false,
        "httpOnly": true,
        "name": "dfpfpt",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "2cd9a9685d024485a9e98178488157de"
    },
    {
        "domain": ".www.linkedin.com",
        "expirationDate": 1779546370.056233,
        "hostOnly": false,
        "httpOnly": false,
        "name": "JSESSIONID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "\"ajax:0308958622005136793\""
    },
    {
        "domain": ".linkedin.com",
        "expirationDate": 1763562976.610032,
        "hostOnly": false,
        "httpOnly": false,
        "name": "li_mc",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "MTsyMTsxNzQ4MDEwOTc1OzE7MDIxGlmyhsfnUfY88i+FxfKS9vj9PcfwqLFUb/p8CVel6Bs="
    },
    {
        "domain": ".linkedin.com",
        "expirationDate": 1755787271.258892,
        "hostOnly": false,
        "httpOnly": false,
        "name": "li_sugr",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "4ab6d326-2a44-40e9-a1c1-aebabb9c49cb"
    },
    {
        "domain": ".www.linkedin.com",
        "expirationDate": 1763563269,
        "hostOnly": false,
        "httpOnly": false,
        "name": "li_theme",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "dark"
    },
    {
        "domain": ".www.linkedin.com",
        "expirationDate": 1763563269,
        "hostOnly": false,
        "httpOnly": false,
        "name": "li_theme_set",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "user"
    },
    {
        "domain": ".linkedin.com",
        "expirationDate": 1779546370.056171,
        "hostOnly": false,
        "httpOnly": false,
        "name": "liap",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "true"
    },
    {
        "domain": ".www.linkedin.com",
        "expirationDate": 1749220869,
        "hostOnly": false,
        "httpOnly": false,
        "name": "timezone",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "Asia/Colombo"
    },
    {
        "domain": ".linkedin.com",
        "expirationDate": 1750603270,
        "hostOnly": false,
        "httpOnly": false,
        "name": "UserMatchHistory",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "AQIFi22Q4PJgxAAAAZb9lz9Xykc6P_9h53xJmFM2ORHWm2dkJk7IUrH5Rh0LI3tfjxbcZs04Z_kKe5PrivXIhrPXTXbtf-b4nwKBFkJXiZuZr4F9biPO8QLDmv1zvMbYxq0x365sDKj52MhS8hu1wLdgK1SZAJCqQfiJbsoiqjqUObfrHhgQGdG0UWcGQ4X4Pqjz6WoZLFbVLevPRIsFJ26u0WnfMGGIE_N_9SHx_vkuPD5M9RcSDAftRgr4D10fPaTfWE2rhoQTrji5cYq9MLGaEmCOcwBWTLUZKCW3M3xiexmMhFISoyfPur9a7ssvOaySQ7WmkhfEiqPMfLggtDQFUppRIkELWFjSvuiKwSWRJZI_ZA"
    }
]